### ISSUE TITLE
Some text are white on white background.

### ISSUE THREAD

**Issue by ruifung** [MediaBrowser/emby-web-mobile#1]
Like the ones in playback settings, etc. Theres quite a few.

**Comment by LukePulverenti** [comment]
Hi, can you show a screenshot example? have you tried clearing browsing data? what browser?

**Comment by ruifung** [comment]
Browser, Opera.
As far as I can tell, pretty much every dropdown that should be dark colored background is white for some reason.

![image](https://cloud.githubusercontent.com/assets/1073945/14063038/eb8b8a68-f3f1-11e5-8836-50d013a87de9.png)
![image](https://cloud.githubusercontent.com/assets/1073945/14063039/f6d783c2-f3f1-11e5-88d6-ae04b39a33b2.png)
![image](https://cloud.githubusercontent.com/assets/1073945/14063048/2d39db04-f3f2-11e5-948e-f181a48ec037.png)

**Comment by LukePulverenti** [comment]
This is resolved now, thanks for the report.
